### ISSUE TITLE
Error: Path '' does not exist

### ISSUE THREAD

**Issue by Who-Dares-Marketing** [MarkEdmondson1234/verbal_ga_shiny#1]
Trying to set the client secrets for the Auth and the above error keeps cropping up.  Below is the code for the app.r file and I've also put my .Renviron file below as well as I think that could also be an issue.  I have my I have my "auth" json files in a folder called "auth". 

app.r:
```
library(shiny) #R Web Apps
library(googleAuthR) #Handles Google Authorisation Requests


gar_set_client(scopes = c("https://www.googleapis.com/auth/analytics.readonly"))


# Define UI for application
ui <- fluidPage(
  gar_auth_jsUI("auth")
   

)

# Define server logic
server <- function(input, output) {

   #get auth token
   auth <- callModule(gar_auth_js, "auth")
  
}

# Run the application 
shinyApp(ui = ui, server = server)
```

.Renviron:

`GAR_CLIENT_WEB_JSON= "auth/auth.json"`

**Comment by MarkEdmondson1234** [comment]
Are you using RStudio projects?  

It could be the folder you are calling the Shiny script from is not the one assumed. 

I guess it is the line `gar_set_client()` that has the error?

Could you run `getwd(); list.files(full.names = TRUE, recursive = TRUE)` in the folder where your Shiny app sits and report it here, to check the files are in the right places.

Also please report the libraries you have loaded, via `sessionInfo()` in case its that.

**Comment by Who-Dares-Marketing** [comment]
Hi Mark,

Thanks for the response, really appreciated.

I've set the app up in a R Studio project yes, double checked and the things like the .Rproj files are there.

Yes its the gar_set.. line that has the error, runs fine when blocked out.

Have run the getwd() command and it returns the img attached. Also ran the session() command and the return is attached. 

Packages installed are library(shiny) and library(googleAuthR).

Thanks so much for your help!

Cameron
![getwd_picture](https://user-images.githubusercontent.com/35102480/41842419-a4ff7b98-7862-11e8-879a-5eb1e3c74e24.JPG)
![session_info](https://user-images.githubusercontent.com/35102480/41842420-a525552a-7862-11e8-9a3d-2427a3ceefd8.JPG)

**Comment by MarkEdmondson1234** [comment]
I think you just need to update to googleAuthR 0.6.3, it came out last week with a fix for this.

________________________________

**Comment by Who-Dares-Marketing** [comment]
Worked a treat! Thanks Mark.  I'll file that one under school boy error!
