### ISSUE TITLE
google OAuth 2.0 authentication issue

### ISSUE THREAD

**Issue by afzal-joy** [MarkEdmondson1234/verbal_ga_shiny#2]
![oauth](https://user-images.githubusercontent.com/25547618/42123815-0a7d42d6-7c76-11e8-9988-10b99f73778a.png)

file structure

- appfolder (which is in home directory)
  - app.r
  - .Renviron
  - json
 

 

.Renviron file  code

`GAR_CLIENT_WEB_JSON="webapp_client_secret_id.json"`

app.r file code

`library(shiny)`
`library(googleAuthR)`
`gar_set_client(scopes=c("https://www.googleapis.com/auth/analytics.readonly"))`
 
`ui <- fluidPage( )`
`server <- function(input, output) { }`
`shinyApp(ui = ui, server = server)`

`Error in gar_set_client(scopes = c("https://www.googleapis.com/auth/analytics.readonly")) : 
  No client JSON files found`

**Comment by MarkEdmondson1234** [comment]
Could you report your ‘sessionInfo()’ - perhaps need to update to version that came out a couple of weeks ago.

**Comment by MarkEdmondson1234** [comment]
Also see what `Sys.getenv("GAR_CLIENT_WEB_JSON")` returns - you also need to restart the R session for the environment arguments to be read.   Please also report what is in the JSON file, editing out anything sensitive like AUTH keys.

**Comment by afzal-joy** [comment]
Sys.getenv("GAR_CLIENT_WEB_JSON") was empty.
Restarting the seesion resolved the issue. 

thanks mate project has been loaded, really appreciate it.
