### ISSUE TITLE
Drop down menus not populating.

### ISSUE THREAD

**Issue by collinberke** [MarkEdmondson1234/verbal_ga_shiny#4]
Hello Mark,

   Thanks for this great resource. I'm having trouble populating the drop down menus with the account information for my app. Authentication seems to be working, but the with_shiny(ga_account_list, shiny_access_token = auth() seems to not be pulling in data. Do you have any insight on how I might fix this?

**Comment by MarkEdmondson1234** [comment]
Hi Colin :)

I would try the GA calls outside of Shiny first to check you can authenticate and view your accounts ok.  It sounds as if the email you are authenticating with has no access?  

Can you complete the Getting started video here? http://code.markedmondson.me/googleAnalyticsR/v4.html

**Comment by collinberke** [comment]
Hello Mark,

   Thanks for getting back to me. We've been able to access our account list outside of our shiny app while just using GoogleAnalyticsR and GoogleAuthR. We have been pulling data for accounts this way for awhile now--so we know we have authentication and can pull our GA data outside of running our app. However, when the ga_account_list is wrapped in the with_shiny call and our app is run, the drop-down menus won't populate during the session.

   The account we are working with does have a bunch of web properties associated with the email. Might this have something to do with it?

   Thanks again for any help or direction you might provide.

**Comment by MarkEdmondson1234** [comment]
Hmm it should work, try putting a `browser()` command in the auth function of the Shiny app to inspect the state of the function, see if its pulling back a data.frame of your accounts.  Can you create a minimal example so I can check its not a bug?

**Comment by collinberke** [comment]
Hey Mark. We figured it out! We were adapting your code for a Shiny app similar to yours. On our UI side we were using a submitButton() call. Long story short, we learned a hard lesson today--don't use submit buttons in your shiny app. Here are some references: rstudio/shiny#303 rstudio/shiny#1426.

Thanks for your help. You can close the ticket.

**Comment by MarkEdmondson1234** [comment]
Ah great, glad it got sorted :)


________________________________
